### ISSUE TITLE
alternative drive url for weight file

### ISSUE THREAD

**Issue by JEONG8652** [bcmi/ArtoPIH-Painterly-Image-Harmonization#1]
Hello. Thank you for your great work.

I would like to try testing pretrained ArtoPIH, but I cannot download from Baidu cloud since I can't create an account.
would you mind uploading the weight file on alternative drive (ex. Google Drive)?

Thank you.

**Comment by ustcnewly** [comment]
We have uploaded the model to OneDrive.

**Comment by ustcnewly** [comment]
Thanks for your interest in our work. We have uploaded the model to OneDrive.

 

Best regards,

Li Niu

 

 

发件人: Jaehee_Jeong ***@***.***> 
发送时间: 2024年5月30日 0:13
收件人: bcmi/ArtoPIH-Painterly-Image-Harmonization ***@***.***>
抄送: Subscribed ***@***.***>
主题: [bcmi/ArtoPIH-Painterly-Image-Harmonization] alternative drive url for weight file (Issue #1)

 

Hello. Thank you for your great work.

I would like to try testing pretrained ArtoPIH, but I cannot download from Baidu cloud since I can't create an account.
would you mind uploading the weight file on alternative drive (ex. Google Drive)?

Thank you.

**Comment by JEONG8652** [comment]
Thank you for uploading the weight file, can you please upload the datasets too?

**Comment by ustcnewly** [comment]
We have provided the onedrive link.
